title: Koučing
author: Jaroslav Henner
description: Prožít svoje dobré sny.
google_analytics: G-CSG1PGF4R7

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

collections:
  staff_members:
    people: true
    output: true