title: Koučing
author: Jaroslav Henner
description: Koučing vám umožní najít vybrat si tu Vaši cestu životem, kariérou či osobní transformací a překonávat překážky které potkáte.

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

collections:
  staff_members:
    people: true
    output: true