title: Koučing
author: Jaroslav Henner
description: Vaše cesta od problému k řešení.

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

collections:
  staff_members:
    people: true
    output: true